name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare apt
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.10.1
        with:
          required-ros-distributions: humble

      - name: Create workspace
        run: |
          mkdir -p ros2_ws/src/text_stats_node
          rsync -av --exclude='.git' --exclude='.github' ./ ros2_ws/src/text_stats_node/

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          colcon build

      - name: Test
        run: |
          source /opt/ros/humble/setup.bash
          source ros2_ws/install/setup.bash
          ros2_ws/src/text_stats_node/test/test.bash

